# Generated by Django 4.1.7 on 2023-03-18 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipment",
            name="Customer",
        ),
        migrations.AddField(
            model_name="orders",
            name="Shipment",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="customer.shipment",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="Country",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipments",
                to="customer.country",
            ),
            preserve_default=False,
        ),
    ]
