# Generated by Django 4.1.7 on 2023-03-18 11:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0002_remove_shipment_customer_orders_shipment_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shipment",
            old_name="Country",
            new_name="country",
        ),
    ]
