# Generated by Django 4.1.7 on 2023-03-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0003_rename_country_shipment_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="full_name",
        ),
        migrations.AddField(
            model_name="customer",
            name="username",
            field=models.CharField(
                db_index=True, default=1, max_length=255, unique=True
            ),
            preserve_default=False,
        ),
    ]
