# Generated by Django 4.1.7 on 2023-03-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0005_customer_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="full_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
