# Generated by Django 4.1.7 on 2023-03-18 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artiste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("profile", models.ImageField(upload_to="artist/img")),
                ("is_artist", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
                ("release_date", models.DateTimeField(auto_now_add=True)),
                ("number_songs", models.IntegerField(blank=True, null=True)),
                (
                    "cover_img",
                    models.ImageField(
                        height_field="400", upload_to="product/img", width_field="400"
                    ),
                ),
                ("producer", models.CharField(blank=True, max_length=150, null=True)),
                ("intro_video", models.FileField(upload_to="product/video")),
                ("bio", models.TextField()),
                ("director", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="artiste.artiste",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song_title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="songs")),
                ("cover_art", models.ImageField(upload_to="cover_art")),
                (
                    "description",
                    models.TextField(blank=True, max_length=1024, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("number_of_artiste", models.IntegerField(blank=True, null=True)),
                ("length", models.IntegerField(blank=True, null=True)),
                ("featured", models.CharField(max_length=255)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to="artiste.product",
                    ),
                ),
            ],
        ),
    ]
