# Generated by Django 4.1.7 on 2023-03-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artiste", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cover_img",
            field=models.ImageField(upload_to="product/img"),
        ),
    ]
