# Generated by Django 4.1.7 on 2023-03-21 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0006_customer_full_name"),
        ("artiste", "0002_alter_product_cover_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="orders",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="customer.orders",
            ),
            preserve_default=False,
        ),
    ]
